### ISSUE TITLE
Support for Zod Schema `.transform`

### ISSUE THREAD

**Issue by dvargas92495** [asteasolutions/zod-to-openapi#120]
Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@asteasolutions/zod-to-openapi@4.5.3` for the project I'm working on.

I wanted to use `.transform()` for my zod schema, which broke the openapi generator. Here's an example:
```typescript
limit: z
    .number()
    .optional()
    .openapi({
      description: "Number of results to return. Always default to 3 unless specified otherwise by the user.",
      type: "integer",
    })
    .default(3)
    .transform((v) => v.toString())
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js b/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js
index d82c957..23f5a53 100644
--- a/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js
+++ b/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js
@@ -641,7 +641,7 @@ class OpenAPIGenerator {
             return this.unwrapChained(schema._def.innerType);
         }
         if ((0, zod_is_type_1.isZodType)(schema, 'ZodEffects') &&
-            schema._def.effect.type === 'refinement') {
+           ['refinement', 'transform'].includes(schema._def.effect.type)) {
             return this.unwrapChained(schema._def.schema);
         }
         return schema;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Happy to turn this into the PR if you approve of the suggestion

**Comment by AGalabov** [comment]
@dvargas92495 to be honest we previouslly labeled this as "unsupported" and I can't even fully remember why. And it was actually brought as a topic in [this PR](https://github.com/asteasolutions/zod-to-openapi/pull/118#issue-1669555907) just a few days ago. So we are definitely planning to try and support this. I am not sure if that is the only change we'd need to make but you could go ahead and give it a go with a PR.

Some notes:
1. This is mentioned in the README and would need to be updated there as well. 
2. We maintain a sort of a TDD approach in this repository since the expected state is pretty obvious. There is a `transform.spec.ts`. You would need to go ahead and modify it, presumably some more tests might occur as well.

**Comment by AGalabov** [comment]
It should now be available in [v4.7.0](https://github.com/asteasolutions/zod-to-openapi/releases/tag/v4.7.0)

**Comment by codeinabox** [comment]
I am trying to use a transform with a query schema but the following error:

> TS2740: Type 'ZodEffects<ZodObject<{ fromDttmUTC: ZodEffects<ZodString, Instant, string>; toDttmUTC: ZodEffects<ZodString, Instant, string>; }, "strip", ZodTypeAny, { ...; }, { ...; }>, { ...; }, { ...; }>' is missing the following properties from type 'ZodObject<any, any, any, { [x: string]: any; }, { [x: string]: any; }>': _cached, _getCached, shape, strict, and 14 more.

Below is the schema

```ts
export const querySchema = z
  .object({
    fromDttmUTC: z.date(),
    toDttmUTC: z.date(),
  })
  .transform(({ fromDttmUTC, toDttmUTC }) => ({
    range: {
      from: fromDttmUTC,
      to: toDttmUTC,
    },
  }));
```

**Comment by AGalabov** [comment]
@codeinabox are you passing this directly to `request.query`. We only support a ZodObject there. Internally each key can have a transform on its own but not the whole object.

It might be possible to add a support for ZodEffect where the base was a ZodObject. Would you open up a new issue that specifies this particular usage and I'll see what can we do.
