### ISSUE TITLE
How to specify Swagger AnyType

### ISSUE THREAD

**Issue by Siegrift** [asteasolutions/zod-to-openapi#131]
I have a schema which returns a field which can be "any" type. In openAPI you can do this via https://swagger.io/docs/specification/data-models/data-types/#any

My zod schema looks like this:
```ts
export const errorSchema = z
  .object({
    error: z.string().openapi({ description: 'Brief description of the error.', example: 'Validation error' }),
    context: z
      .any()
      .openapi({
        type: undefined as any,
        description: 'Optional additional context for the error - for example validation errors.',
        example: '<valid-json-with-any-structure>',
      })
      .optional(),
  })
  .strict();
```

This is not accepted and I get the following error:
```sh
Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.
```
<img width="952" alt="image" src="https://github.com/asteasolutions/zod-to-openapi/assets/22679154/3f943f13-90f4-46c1-8481-9aed607d7e47">

**Comment by AGalabov** [comment]
@Siegrift  I am going to provide you with a multitude of options since I am not sure what would work best for you:

# Providing type manually
When you provide a `type` manually you do not want to pass `"undefined"` as in the value `undefined` with a Typescript type of any. What you do want to provide is the string value `'any'` (as in what needs to be added into the document).

So  in general passing a `type` should look like this: 
```ts
context: z
      .any()
      .openapi({
        type: 'any',
        description: 'Optional additional context for the error - for example validation errors.',
        example: '<valid-json-with-any-structure>',
      })
      .optional(),
```

# Any does not seem to be a valid type

The above being said I do not think that `'any'` is a correct type. Based on https://swagger.io/docs/specification/data-models/data-types/#any I see that it should either be left empty or `anyOf` should be used. So I guess for `z.any()` you can do the following as the most semantically correct approach:
```ts
.openapi({
  anyOf: [
    { type: 'string' },
    { type: 'number' },
    { type: 'integer' },
    { type: 'boolean' },
    { type: 'array', items: {} },
    { type: 'object' },
  ],
});
```

# Any is a bad practice in Typescript

I am a very opinionated Typescript fan. Overall using `any` is kind of an anti pattern in my opinion - you are just going back to JS. What I would suggest is using `unknown` - and for an API this is a slightly better approach. And if you do use `z.unknown()` then you would get the empty type out of the box since we've added the support for it. 

Let me know what you think and if you need more information on any of the above topics

**Comment by Siegrift** [comment]
Hi, thanks for the response - the last option is what I wanted, but I didn't know I could use that :)  

I actually tried both option 1) and 2), but they had some limitations. Writing it down just for the sake of completeness.

1. Providing type manually

I could pass `"any"` but then I would end up with `any` in the swagger (and that is not a valid swagger type). Also, the typings for the openAPI `type` are quite strict so I'd need to use `as any`, which feels a bit wierd (but iI wouldn't mind it if it accomplished the use case).

2. Using `anyOf`

Leads to the same issue as in the original description. If you use `anyOf`, there is no `type` so I end up with the ```Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.``` error again.
