### ISSUE TITLE
`nullable` in `union` causes extra `nullable` in document

### ISSUE THREAD

**Issue by MattIPv4** [asteasolutions/zod-to-openapi#149]
👋 When using a union that contains a nullable data type, the generated document contains the nullable data type, as well as an extra nullable.

`z.union([ z.number().nullable(), z.boolean().nullable() ])` results in `[{type: "number", nullable: true}, {type: "boolean", nullable: true}, {nullable: true}]`, I would expect it to generate `[{type: "number", nullable: true}, {type: "boolean", nullable: true}]`

https://runkit.com/mattipv4/64877284e730f70008197f5e

**Comment by AGalabov** [comment]
@MattIPv4  thank you for bringing this up. This is a very peculiar behavior. Overall the problem is that apparantly `z.union` is quite smart and if any of the underlying schemas is  `.nullable` then the `.isNullable()` getter of the whole union would also return `true`. This is unlike the rest of the behavior we've observed with other schemas. 

And looking at that design decision by `zod` and what we currently do with "nullable unions" I think a more appropriate representation would be:

```json
anyOf: [{ type: 'number' }, { type: 'boolean' }, { nullable: true }],
```

and for 3.1.0 this would be:

```json
anyOf: [{ type: 'number' }, { type: 'boolean' }, { type: 'null' }],
```

Would you agree with that?
