### ISSUE TITLE
bearer token is not including in header while sending request

### ISSUE THREAD

**Issue by DebXD** [asteasolutions/zod-to-openapi#187]
help needed. I am a beginner trying to create swagger docs in hono.js but facing difficulties.
It is showing authorization field in web ui but it is not taking the input which user puts in this field.
So the api returning no authorization token included in the request

```
const authTokenSchema = z.object({
	Authorization: z.string().refine((value) => value.startsWith("Bearer "), {
		message: "Invalid Authorization header",
	}),
});


swagger.openapi(
	createRoute({
		method: "get",
		path: "/me",
		tags: ["Users"],
		summary: "Get user details",

		request: {
			required: true,
			headers: authTokenSchema,
			description:
				"Include a Bearer token in the 'Authorization' header. For example: 'Bearer YOUR_TOKEN_HERE'",
		},
		responses: {
			200: {
				description: "Respond with a message",
				content: {
					"application/json": {
						schema: z.object({
							message: z.string(),
						}),
					},
				},
			},
			401: {
				description: "Unauthorized",
				content: {
					"application/json": {
						schema: z.object({
							error: z.string(),
						}),
					},
				},
			},
		},
	}),
	(c) => {
		
		return c.jsonT({
			message: "hello",
		});
	},
);
`````

**Comment by AGalabov** [comment]
Hello @DebXD saddly I do not think we can help you here. What our library does is to generate a valid OpenAPI/Swagger JSON based on zod schemas. As such the best I can say is that your code is valid apart from the irregular usage of 
```
required: true,
description: "Include a Bearer token in the 'Authorization' header. For example: 'Bearer YOUR_TOKEN_HERE'",
```
if you were using Typescript you'd see that those are not allowed properties. However that is not a problem but any means - it is just that those have no effect on your documentation. If you want to add them you probably want to have the following

```
const authTokenSchema = z.object({
  Authorization: z
    .string()
    .refine(value => value.startsWith('Bearer '), {
      message: 'Invalid Authorization header',
    })
    .openapi({
      description:
        "Include a Bearer token in the 'Authorization' header. For example: 'Bearer YOUR_TOKEN_HERE'",
    }),
});
```

and then simply: 
```
  request: {
    headers: authTokenSchema,
  },
```

Note that the description has been moved to the exact Authorization parameter and `required` is obsolete since you are using a required schema - z.string().

But then again our library has nothing to do with "while sending request" so you'd have to look into your code and related libraries (hono.js) for answers.

Sorry, good luck and let us know if you face any problems with the library in the future.
