### ISSUE TITLE
How to use the schema in request.Body

### ISSUE THREAD

**Issue by nazarEnzo** [asteasolutions/zod-to-openapi#20]
Hi. Sorry for the simple question. Can you please tell me how I can do the same thing as in the yaml file:
```
...
requestBody:
   required: true
   content:
     application/json:
         schema:
             $ref: "#/components/schemas/Address"
...
```

I tried to connect the scheme in the same way as in _responses_ section  but got an error.

```
registry.registerPath({
 ...
  requestBody: {
    content: {
      "application/json": {
        schema: Schemes.AddressSchema.openapi({
          description: "Object with Address data.",
        }),
      },
    },
  },
  responses: {
    200: {
      mediaType: "application/json",
      schema: Schemes.AddressSchema.openapi({
        description: "Object with Address data.",
      }),
    },
})
```
Thank you!

**Comment by AGalabov** [comment]
Hello again @nazarEnzo

I believe this is what you're looking for:

```ts
request: {
    body: schema: Schemes.AddressSchema.openapi({
      description: "Object with Address data.",
    })
  }
   responses: {
     200: {
       mediaType: "application/json",
       schema: Schemes.AddressSchema.openapi({
         description: "Object with Address data.",
       }),
     },
```

Basically all of `body`, `params`, `query` and headers are passed as an object for the `request` key. There is some information about it in the [Registering a path](https://github.com/asteasolutions/zod-to-openapi#registering-a-path) section of the README.md file. As for the content type we are only supporting `application/json` for simplicity of usage since this is the most obvious case and we haven't had a the need for anything else as of now.

Thank you for using `@asteasolutions/zod-to-openapi`

**Comment by nazarEnzo** [comment]
Hello @AGalabov. Thank you for your help!

I tried what you suggested and apparently i am doing something wrong again :)

![image](https://user-images.githubusercontent.com/104757580/174969177-2fa64993-2963-4910-8bc1-36c9555fa317.png)

**Comment by nazarEnzo** [comment]
@AGalabov 

It seems to work for me. Is it a good way to reach my goal?
```
  request: {
    body: z.object({
      schema: Schemes.AddressSchema.openapi({
        description: "Object with Address data.",
      }),
    }),
  },
```

**Comment by nazarEnzo** [comment]
Everything worked out. Thank you for your help and a great product.
