### ISSUE TITLE
Support for importing external types

### ISSUE THREAD

**Issue by RamonBalthazar** [asteasolutions/zod-to-openapi#280]
Is there a way of registering a component that resolves to importing a type from some specified path?

We have some complex types from an external system that get synced frequently. These types are trusted, but we can't create Zod schemas for them, so I was hoping we could import them in the generated schema.

**Comment by AGalabov** [comment]
@RamonBalthazar in the dawn of this library we were rewriting a project in our company so that we can automatically generate documentation instead of manually writing yamls. So what I can suggest to you is to figure out a way to create the schema for them and use a tool like https://www.npmjs.com/package/openapi-merge or something similar to build our document and then combine it with whatever you have. I think that would suite your needs best. We do not plan to implement this. Good luck :rocket:
