### ISSUE TITLE
Support for allOf & discriminator

### ISSUE THREAD

**Issue by joeydebreuk** [asteasolutions/zod-to-openapi#29]
Is there support for `allOf` & `discriminator`? If so, can you provide an example?

EG I want to achieve spec:

```
Animal:
  discriminator:
    propertyName: type
  type: object
  properties:
    name:
      type: string
    type:
      type: string
      enum:
        - dog
        - cat
Dog:
  discriminator:
    propertyName: type
  allOf:
    - $ref: '#/components/schemas/Animal'
    - type: object
      properties:
        type:
          type: string
          const: dog
      required:
        - type
```

**Comment by AGalabov** [comment]
@joeydebreuk thank you for using `zod-to-openapi`.

Saddly there is no such support right now. Basically with extended schemas we took the approach of just generating the full object (i.e duplicating their schemas). There is no problem when validating because if you already have `zod` you can use it to validate your data. And in that case there would be no need for the `discriminator` in the documentation since you can use `union/`discriminatedUnion`.

Having said that I will take a more in depth look at  your request when I find the time to research the generated zod schema from an extended object (if we have some metadata that we can use) and write back to you.

**Comment by AGalabov** [comment]
Hello again @joeydebreuk,

We added support for extended schemas in the PR linked to your issue. The discriminator part is OpenApi specific and can be added using the `.openapi` method. A unit test with your exact example can be seen [here](https://github.com/asteasolutions/zod-to-openapi/blob/master/spec/polymorphism.spec.ts#L86).

Please feel free to test it out by upgrading to version 1.4.0.

Thany for using `@asteasolutions/zod-to-openapi` and reporting this.

**Comment by joeydebreuk** [comment]
Thanks @AGalabov !
